pipeline:
  identifier: Build_elubik_harness_python_1720628300398
  name: Build harness-python
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: elubik/harness-python
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      echo "Welcome to Harness CI"
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  type: RunTests
                  name: RunTests
                  identifier: RunTests
                  spec:
                    language: Python
                    buildTool: Pytest
                    runOnlySelectedTests: true
                    enableTestSplitting: false
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: luabik_priv
                    repo: luabik/harness-python-demo
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        description: ""
